services:
  nginx:
    image: nginx:latest
    volumes:
      - ./configuration/nginx:/etc/nginx/conf.d
    ports:
      - 8080:80
    links:
      - wordpress
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    volumes:
      - ./plugins/:/var/www/html/wp-content/plugins/
      - ./themes/:/var/www/html/wp-content/themes/
      - ./data/html:/var/www/html
    ports:
      - "80:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: "${DBUSER}"
      WORDPRESS_DB_PASSWORD: "${DBUSERPASS}"
      WORDPRESS_DB_NAME: "${DBNAME}"
      WORDPRESS_TABLE_PREFIX: "${DBPREF}"
      WORDPRESS_DEBUG: "${WP_DEBUG}"
  db:
    image: mysql:5.7
    volumes:
      - ./data/mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "${DBPASS}"
      MYSQL_DATABASE: "${DBNAME}"
      MYSQL_USER: "${DBUSER}"
      MYSQL_PASSWORD: "${DBUSERPASS}"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    links:
      - db:mysql
    ports:
      - "8081:80"
    environment:
      MYSQL_ROOT_PASSWORD: "${DBPASS}"